In [1]:
from unityagents import UnityEnvironment
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

env = UnityEnvironment(file_name="Tennis_Windows_x86_64/Tennis.app")

# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: TennisBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 


In [2]:
import torch
from network import Actor

actor_0 = Actor(2, 24, 300, 200)
actor_1 = Actor(2, 24, 300, 200)

checkpoint = torch.load('model_dir/0.05_score_episode-9999.pt')
actor_0.load_state_dict(checkpoint[0]['actor_params'])
actor_1.load_state_dict(checkpoint[1]['actor_params'])
actor_0.eval()
actor_1.eval()

Actor(
  (fc1): Linear(in_features=24, out_features=300, bias=True)
  (fc2): Linear(in_features=300, out_features=200, bias=True)
  (fc3): Linear(in_features=200, out_features=2, bias=True)
)

In [4]:
for episode in range(5):
    env_info = env.reset(train_mode=False)[brain_name]
    
    states = env_info.vector_observations
    obs = [agent_obs for agent_obs in states]
    
    for episode_t in range(100):

        #actions_array = np.stack([agent(torch.tensor(ob).float()).detach().numpy() for agent,ob in zip([actor_1,actor_2],obs)])

        agent_0_action = actor_1(torch.from_numpy(obs[0]).float()).detach().numpy()
        agent_1_action = actor_1(torch.from_numpy(obs[1]).float()).detach().numpy()
        
        actions_array = np.stack([agent_0_action,agent_1_action])
        
        env_info = env.step(actions_array)[brain_name]  

        next_states = env_info.vector_observations
        next_obs = [agent_obs for agent_obs in next_states]

        #rewards = np.array(env_info.rewards)
        
        dones = np.array(env_info.local_done)

        obs = next_obs
        
        #reward_this_episode += rewards
        
        if np.any(dones):
            break

In [7]:
import torch
import numpy as np
torch.tensor(np.zeros(10)).to('cpu').to('cuda')

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0',
       dtype=torch.float64)

In [3]:
from maddpg import MADDPG
maddpg = MADDPG(2, 24)

In [ ]:
maddpg.to_categorical(rewards, probs, dones):

In [ ]:
obs, action, reward, next_obs, done = map(transpose_to_tensor, samples) # get data

# full versions of obs are needed for the critics
obs_full = torch.cat(obs, 1)
next_obs_full = torch.cat(next_obs, 1)

agent = self.maddpg_agent[agent_number] # set the agent
agent.critic_optimizer.zero_grad()

# Calculate log probability DISTRIBUTION w.r.t. stored actions
log_probs = '''agent.critic(obs, actions, log=True)'''

target_actions = self.target_act(next_obs) # produces target actions using both critics for the next state, i.e. a(t+1)
target_actions = torch.cat(target_actions, dim=1) # concatinates them together

# Calculate TARGET distribution/project onto supports (Yi)
target_probs = agent.critic_target(next_obs_full, target_actions).detach()

In [5]:
env.close()

In [70]:
act = 1.0
noise = 0.2

In [71]:
act + noise > 1

1.2

In [74]:
np.random.beta(1,1,2)

array([0.47998014, 0.15635096])

In [1]:
import numpy as np

array([-0.38301368,  0.52538875])

In [77]:
0.9**0.5

0.9486832980505138

In [1]:
from OUNoise import OUNoise

In [2]:
noise_process = OUNoise(2)

In [50]:
noise_process.noise()

tensor([0.2083, 0.0736])

In [104]:
actor_2(torch.from_numpy(obs[1]).float())

tensor([-0.9999, -0.6677], grad_fn=<TanhBackward>)

In [105]:
noise

tensor([-0.0512,  0.0120])

In [103]:
action = actor_2(torch.from_numpy(obs[1]).float())
noise = noise_process.noise()

action += noise_scale*(noise-action)
torch.clamp(action,-1,1)

tensor([-0.5256, -0.3278], grad_fn=<ClampBackward>)

In [55]:
np.random.beta(5)

<function RandomState.beta>

In [64]:
action = -1*action.numpy()

In [148]:
action

array([0.5256, 0.3278], dtype=float32)

array([1., 1.], dtype=float32)

In [139]:
scale = 10

In [3]:
from noise import BetaNoise
import torch
import numpy as np

In [118]:
action = torch.tensor([-0.5256, 0.3278])
action

tensor([-0.5256,  0.3278])

In [200]:
BetaNoise(action.numpy(),noise_scale=0.001)

array([-0.52991087,  0.28001825])

In [ ]:
-1 -> 1

In [87]:
noise_scale=1000
sign = np.sign(action)                              # tracking the sign so we can flip the samples later
action = abs(action)                                # we only use right tail of beta

alpha = 1/noise_scale                               # this determines the how contentrated the beta dsn is
value = 0.5+action/2                                # converting from action space of -1 to 1 to beta space of 0 to 1
beta = alpha*(1-value)/value                        # calculating beta
beta = beta + 0.5*((alpha-beta)/alpha)              # adding a little bit to beta prevents actions getting stuck at -1 or 1
sample = np.random.beta(alpha, beta)                # sampling from the beta distribution
#sample = sign*sample+(1-sign)/2                     # flipping sample if sign is <0 since we only use right tail of beta dsn

action_output = 2*sample-1                          # converting back to action space -1 to 1

In [203]:
torch.tensor(action.numpy())

tensor([-0.5256,  0.3278])

In [191]:
sign

tensor([-1., -1.])

array([0.94245522, 0.83024576])

In [204]:
sample

array([0.05754478, 0.16975424])